name: flutter_zod
description: A Zod-inspired validation library for Flutter with schema-based form handling.
version: 1.0.0
repository: https://github.com/shamnad-sherief/flutter_zod

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
